# Generated by Django 2.0.2 on 2018-02-22 22:43

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='reference_code',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddField(
            model_name='domain',
            name='reference_code',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('name', 'chapter__name')),
        ),
    ]
