# Generated by Django 2.0.2 on 2018-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chronicle',
            options={'verbose_name': 'Chronicle'},
        ),
        migrations.AlterField(
            model_name='prestigereport',
            name='end',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestigereport',
            name='start',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='prestige',
            unique_together={('report', 'membership')},
        ),
    ]
