# Generated by Django 2.0.2 on 2018-03-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestigelevel',
            old_name='level',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='prestigelevel',
            unique_together={('organization', 'name')},
        ),
    ]
