# Generated by Django 2.0.4 on 2018-04-13 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronicle',
            name='rules_url',
        ),
        migrations.RemoveField(
            model_name='chronicle',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='rules_url',
        ),
    ]
