# Generated by Django 2.0.2 on 2018-02-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestige',
            old_name='witness',
            new_name='coordinator',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='information',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='reference_code',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='information',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='reference_code',
        ),
        migrations.AddField(
            model_name='chapter',
            name='rules_url',
            field=models.URLField(default='', help_text='URL pointing to the Chapter rules document.', verbose_name='Rules URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='rules_url',
            field=models.URLField(default='', help_text='URL pointing to the Domain game and approval rules.', verbose_name='Rules URL'),
            preserve_default=False,
        ),
    ]
