# Generated by Django 2.0.2 on 2018-02-23 00:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180222_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestige', to='organization.Chapter')),
            ],
            options={
                'verbose_name': 'Prestige Report',
            },
        ),
        migrations.AlterModelOptions(
            name='prestige',
            options={'verbose_name': 'Prestige Line'},
        ),
        migrations.RemoveField(
            model_name='prestige',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='prestige',
            name='created',
        ),
        migrations.RemoveField(
            model_name='prestige',
            name='modified',
        ),
        migrations.AlterField(
            model_name='prestige',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='prestige',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='organization.PrestigeReport'),
            preserve_default=False,
        ),
    ]
