# Generated by Django 2.0.2 on 2018-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180222_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='rules_url',
            field=models.URLField(blank=True, help_text='URL pointing to the Chapter rules document.', verbose_name='Rules URL'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='rules_url',
            field=models.URLField(blank=True, help_text='URL pointing to the Domain game and approval rules.', verbose_name='Rules URL'),
        ),
    ]
