# Generated by Django 2.0.2 on 2018-02-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180228_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestigereport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestige_reports', to='organization.Organization'),
        ),
    ]
