# Generated by Django 2.0.2 on 2018-03-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180228_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('-event_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='prestige',
            options={'ordering': ('membership',), 'verbose_name': 'Prestige Line'},
        ),
        migrations.AlterField(
            model_name='chronicle',
            name='reference_code',
            field=models.SlugField(verbose_name='Unique short name or acronym.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='reference_code',
            field=models.SlugField(verbose_name='Unique short name or acronym.'),
        ),
        migrations.AlterUniqueTogether(
            name='prestige',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='chronicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='organization.Chronicle'),
        ),
        migrations.AlterUniqueTogether(
            name='gameevent',
            unique_together={('number', 'chronicle')},
        ),
    ]
