# Generated by Django 2.0.2 on 2018-02-23 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180222_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestigeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=40)),
                ('prestige_required', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Prestige Level',
                'ordering': ('prestige_required',),
            },
        ),
        migrations.RemoveField(
            model_name='prestigereport',
            name='created',
        ),
        migrations.RemoveField(
            model_name='prestigereport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='prestigereport',
            name='modified',
        ),
        migrations.AddField(
            model_name='chapter',
            name='prestige_cutoff',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestige',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='prestige',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='prestigereport',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AddField(
            model_name='prestigereport',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='prestige',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='prestigelevel',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestige_levels', to='organization.Chapter'),
        ),
        migrations.AlterUniqueTogether(
            name='prestigelevel',
            unique_together={('chapter', 'level')},
        ),
    ]
