# Generated by Django 2.0.2 on 2018-02-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180223_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='prestige_level',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='organization.PrestigeLevel'),
        ),
        migrations.AddField(
            model_name='membership',
            name='prestige_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
