# Generated by Django 2.0.2 on 2018-03-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180301_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevent',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
