# Generated by Django 2.0.2 on 2018-03-02 23:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_auto_20180301_1750'),
        ('organization', '0005_auto_20180302_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('beats', models.PositiveSmallIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_awards', to='sheets.Character')),
                ('game_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_awards', to='organization.GameEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
