# Generated by Django 2.0.2 on 2018-02-23 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180223_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, max_length=20, verbose_name='External ID')),
                ('email_address', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters and Domains'},
        ),
        migrations.AlterField(
            model_name='membership',
            name='external_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organization.Chapter'),
        ),
    ]
