# Generated by Django 2.0.2 on 2018-02-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180223_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='chronicle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='domain',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
