# Generated by Django 2.0.2 on 2018-03-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_experienceaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceaward',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
