# Generated by Django 2.0.2 on 2018-03-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_zero_skills',
            field=models.BooleanField(default=False, help_text='Hide skills with zero dots.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_opt_out',
            field=models.BooleanField(default=False, help_text='Do not send me email notifications'),
        ),
    ]
