# Generated by Django 2.0.2 on 2018-03-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180323_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hide_zero_skills',
        ),
    ]
