# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import systems.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('completed_on', models.DateField(blank=True, editable=False, null=True)),
                ('player_notes', models.TextField(blank=True)),
                ('details', models.TextField(help_text='First 80 characters of the first line will show as a summary.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('spent_experience', models.SmallIntegerField(default=0, verbose_name='Spent Exp')),
                ('version', models.IntegerField(blank='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('information', 'Gather information'), ('resources', 'Gather resources'), ('integrity', 'Develop integrity'), ('aggressive', 'Aggressive action'), ('background', 'Develop background')], max_length=40)),
                ('player_aspiration', models.TextField(blank=True)),
                ('storyteller_response', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyteller_beats', models.SmallIntegerField(default=0, verbose_name='Story beats')),
                ('coordinator_beats', models.SmallIntegerField(default=0, verbose_name='Org beats')),
                ('details', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Character')),
                ('power_stat', systems.fields.DotsField(default=1)),
                ('integrity', systems.fields.DotsField(default=7)),
                ('background', models.TextField(blank=True)),
                ('resource', models.PositiveIntegerField(default=10)),
                ('concept', models.CharField(blank=True, max_length=200)),
                ('faction', models.CharField(blank=True, max_length=200)),
                ('character_group', models.CharField(blank=True, max_length=100)),
                ('strength', systems.fields.DotsField(default=1)),
                ('dexterity', systems.fields.DotsField(default=1)),
                ('stamina', systems.fields.DotsField(default=1)),
                ('intelligence', systems.fields.DotsField(default=1)),
                ('wits', systems.fields.DotsField(default=1)),
                ('resolve', systems.fields.DotsField(default=1)),
                ('presence', systems.fields.DotsField(default=1)),
                ('manipulation', systems.fields.DotsField(default=1)),
                ('composure', systems.fields.DotsField(default=1)),
                ('academics', systems.fields.DotsField(default=0)),
                ('computer', systems.fields.DotsField(default=0)),
                ('crafts', systems.fields.DotsField(default=0)),
                ('investigation', systems.fields.DotsField(default=0)),
                ('medicine', systems.fields.DotsField(default=0)),
                ('occult', systems.fields.DotsField(default=0)),
                ('politics', systems.fields.DotsField(default=0)),
                ('science', systems.fields.DotsField(default=0)),
                ('athletics', systems.fields.DotsField(default=0)),
                ('brawl', systems.fields.DotsField(default=0)),
                ('drive', systems.fields.DotsField(default=0)),
                ('firearms', systems.fields.DotsField(default=0)),
                ('larceny', systems.fields.DotsField(default=0)),
                ('stealth', systems.fields.DotsField(default=0)),
                ('survival', systems.fields.DotsField(default=0)),
                ('weaponry', systems.fields.DotsField(default=0)),
                ('animal_ken', systems.fields.DotsField(default=0)),
                ('empathy', systems.fields.DotsField(default=0)),
                ('expression', systems.fields.DotsField(default=0)),
                ('intimidation', systems.fields.DotsField(default=0)),
                ('persuasion', systems.fields.DotsField(default=0)),
                ('socialize', systems.fields.DotsField(default=0)),
                ('streetwise', systems.fields.DotsField(default=0)),
                ('subterfuge', systems.fields.DotsField(default=0)),
                ('beats', systems.fields.DotsField(default=0)),
                ('experiences', models.PositiveIntegerField(default=0)),
                ('template_beats', systems.fields.DotsField(default=0)),
                ('template_experiences', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modified_on', models.DateField(auto_now=True)),
                ('health_levels', models.PositiveIntegerField(default=0)),
                ('willpower', systems.fields.DotsField(default=1)),
                ('primary_anchor', models.CharField(blank=True, max_length=40)),
                ('secondary_anchor', models.CharField(blank=True, max_length=40)),
                ('is_current', models.BooleanField(default=True, editable=False)),
                ('chronicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='orgs.Chronicle')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('primary_splat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='systems.SplatOption')),
                ('secondary_splat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='systems.SplatOption')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.Template')),
                ('tertiary_splat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='systems.SplatOption')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterMerit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', systems.fields.DotsField(default=1)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merits', to='sheets.Character')),
                ('merit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='systems.Merit')),
            ],
            options={
                'verbose_name': 'Merit',
            },
        ),
        migrations.CreateModel(
            name='CharacterPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', systems.fields.DotsField(default=1)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='sheets.Character')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='systems.Power')),
            ],
            options={
                'verbose_name': 'Power',
            },
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateField(editable=False, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sheets.Character')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.Event')),
            ],
            options={
                'verbose_name_plural': 'Downtime',
            },
        ),
        migrations.CreateModel(
            name='SkillSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('academics', 'Academics'), ('computer', 'Computer'), ('crafts', 'Crafts'), ('investigation', 'Investigation'), ('medicine', 'Medicine'), ('occult', 'Occult'), ('politics', 'Politics'), ('science', 'Science'), ('athletics', 'Athletics'), ('brawl', 'Brawl'), ('drive', 'Drive'), ('firearms', 'Firearms'), ('larceny', 'Larceny'), ('stealth', 'Stealth'), ('survival', 'Survival'), ('weaponry', 'Weaponry'), ('animal_ken', 'Animal Ken'), ('empathy', 'Empathy'), ('expression', 'Expression'), ('intimidation', 'Intimidation'), ('persuasion', 'Persuasion'), ('socialize', 'Socialize'), ('streetwise', 'Streetwise'), ('subterfuge', 'Subterfuge')], max_length=20)),
                ('speciality', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='sheets.Character')),
            ],
            options={
                'verbose_name_plural': 'Skill Specialities',
                'verbose_name': 'Skill Speciality',
            },
        ),
        migrations.AddField(
            model_name='assistance',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sheets.Character'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.Event'),
        ),
        migrations.AddField(
            model_name='aspiration',
            name='downtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sheets.Downtime'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='sheets.Character'),
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('sheets.approvalrequest',),
        ),
        migrations.AlterUniqueTogether(
            name='downtime',
            unique_together=set([('character', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together=set([('character', 'event')]),
        ),
    ]
