# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 20:27
from __future__ import unicode_literals

from django.db import migrations
import systems.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='size',
            field=systems.fields.DotsField(default=0),
        ),
    ]
