# Generated by Django 2.0.2 on 2018-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='character',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
