# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistance', to='sheets.Character'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistance', to='orgs.Event'),
        ),
    ]
