# Generated by Django 2.0.2 on 2018-04-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor_ballistic',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='armor_general',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
