# Generated by Django 2.0.2 on 2018-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='extra_health_levels',
        ),
        migrations.RemoveField(
            model_name='character',
            name='willpower_dots_spent',
        ),
        migrations.RemoveField(
            model_name='character',
            name='willpower_points_spent',
        ),
        migrations.AddField(
            model_name='character',
            name='willpower',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='willpower_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
