# Generated by Django 2.0.2 on 2018-02-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0001_initial'),
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAnchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='sheets.Character')),
                ('template_anchor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game_rules.TemplateAnchor')),
            ],
            options={
                'verbose_name': 'Anchor',
            },
        ),
    ]
