# Generated by Django 2.0.2 on 2018-02-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='created_by',
        ),
    ]
