# Generated by Django 2.0.2 on 2018-03-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperienceAward',
            new_name='Advancement',
        ),
    ]
