# Generated by Django 2.0.2 on 2018-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='description',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='detail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='total_cost',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='experience_cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
