# Generated by Django 2.0.2 on 2018-04-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='aggravated_damage',
        ),
        migrations.RemoveField(
            model_name='character',
            name='bashing_damage',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lethal_damage',
        ),
    ]
