# Generated by Django 2.0.2 on 2018-03-04 02:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('sheets', '0002_auto_20180303_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('player_request', models.TextField()),
                ('storyteller_response', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_actions', to='sheets.Character')),
                ('game_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_actions', to='organization.GameEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
