# Generated by Django 2.0.2 on 2018-04-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20180406_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetracker',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='resourcetracker',
            name='character',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='sheets.Character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcetracker',
            name='current',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='resourcetracker',
            name='name',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
