# Generated by Django 2.0.2 on 2018-02-28 19:32

from django.db import migrations
import game_rules.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20180228_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='health',
            field=game_rules.fields.DotsField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='willpower',
            field=game_rules.fields.DotsField(default=0),
        ),
    ]
