# Generated by Django 2.0.2 on 2018-02-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_characteranchor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='background',
        ),
        migrations.AddField(
            model_name='character',
            name='player_notes',
            field=models.TextField(blank=True, help_text='These will appear in the printable sheet.'),
        ),
        migrations.AddField(
            model_name='character',
            name='storyteller_notes',
            field=models.TextField(blank=True, help_text='These will not be seen by the player.'),
        ),
    ]
