# Generated by Django 2.0.2 on 2018-02-19 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20180219_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
