# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20161122_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterMerits',
            new_name='CharacterMerit',
        ),
        migrations.AlterModelOptions(
            name='charactermerit',
            options={'verbose_name': 'Merit'},
        ),
    ]
