# Generated by Django 2.0.2 on 2018-02-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_remove_character_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='request',
            new_name='description',
        ),
    ]
