# Generated by Django 2.0.2 on 2018-02-23 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_approvalrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
