# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20160311_2355'),
        ('sheets', '0002_auto_20160311_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='systems.AnchorCategory')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='sheets.Character')),
            ],
        ),
    ]
