# Generated by Django 2.0.2 on 2018-02-21 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0002_characterpower_details'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='approvalrequest',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='response',
        ),
        migrations.RemoveField(
            model_name='character',
            name='damage_track',
        ),
        migrations.RemoveField(
            model_name='character',
            name='health_levels',
        ),
        migrations.RemoveField(
            model_name='character',
            name='perm_willpower_spent',
        ),
        migrations.RemoveField(
            model_name='character',
            name='size',
        ),
        migrations.RemoveField(
            model_name='character',
            name='willpower',
        ),
        migrations.RemoveField(
            model_name='character',
            name='willpower_max',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='aggravated_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='bashing_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='extra_health_levels',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='lethal_damage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='supernatural_energy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='willpower_dots_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='willpower_points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval_requests', to='sheets.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Name or Alias'),
        ),
        migrations.AlterField(
            model_name='character',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.Organization'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
