# Generated by Django 2.0.2 on 2018-02-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20180220_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'verbose_name': 'Approval Request'},
        ),
    ]
