# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 16:23
from __future__ import unicode_literals

from django.db import migrations
import systems.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_character_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='size',
            field=systems.fields.DotsField(default=5),
        ),
    ]
