# Generated by Django 2.0.2 on 2018-03-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20180326_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='prestige_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
