# Generated by Django 2.0.2 on 2018-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20180223_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='attachment',
            field=models.BinaryField(blank=True),
        ),
    ]
