# Generated by Django 2.0.2 on 2018-02-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20180226_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='attachment_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='attachment_filename',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='sheets.Character'),
        ),
    ]
