# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20170414_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='resource_max',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
