# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import systems.fields


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20161122_1934'),
        ('sheets', '0003_auto_20161122_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', systems.fields.DotsField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='sheets.Character')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='systems.Power')),
            ],
            options={
                'verbose_name': 'Power',
            },
        ),
        migrations.AlterField(
            model_name='charactermerit',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merits', to='sheets.Character'),
        ),
    ]
