# Generated by Django 2.0.2 on 2018-02-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20180228_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='resource',
            new_name='resource_start',
        ),
        migrations.RemoveField(
            model_name='character',
            name='willpower_points',
        ),
    ]
