# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import systems.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='beats',
            field=systems.fields.DotsField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='experiences',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='template_beats',
            field=systems.fields.DotsField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='template_experiences',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
