# Generated by Django 2.0.2 on 2018-04-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20180406_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='health',
            new_name='health_boxes',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='willpower',
            new_name='willpower_max',
        ),
        migrations.AlterUniqueTogether(
            name='resourcetracker',
            unique_together={('name', 'character')},
        ),
    ]
