# Generated by Django 2.0.2 on 2018-03-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_downtimeaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtimeaction',
            options={'verbose_name': 'Downtime Action'},
        ),
    ]
