# Generated by Django 2.0.2 on 2018-02-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20180220_2216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character',
            unique_together=set(),
        ),
    ]
