# Generated by Django 2.0.2 on 2018-02-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20180226_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='supernatural_energy',
        ),
    ]
