# Generated by Django 2.0.2 on 2018-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20180228_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='initiative',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_notes',
            field=models.TextField(blank=True, help_text='Shown in player sheet.'),
        ),
    ]
