# Generated by Django 2.0.2 on 2018-04-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20180409_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcetracker',
            options={'verbose_name': 'Resource'},
        ),
        migrations.AlterField(
            model_name='resourcetracker',
            name='name',
            field=models.CharField(editable=False, max_length=40),
        ),
    ]
