# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_character_resource_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='resource',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='resource_max',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
