# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20161122_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='anchor',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='primary_anchor',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='character',
            name='secondary_anchor',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.DeleteModel(
            name='Anchor',
        ),
    ]
