# Generated by Django 2.0.2 on 2018-03-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20180228_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='size',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
