# Generated by Django 2.0.2 on 2018-04-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20180409_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('capacity', models.PositiveSmallIntegerField(default=10)),
                ('bashing_damage', models.PositiveSmallIntegerField(default=10)),
                ('lethal_damage', models.PositiveSmallIntegerField(default=10)),
                ('aggravated_damage', models.PositiveSmallIntegerField(default=10)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='sheets.Character')),
            ],
            options={
                'verbose_name': 'Health',
            },
        ),
    ]
