# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_auto_20170417_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='perm_willpower_spent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='willpower_max',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='willpower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
