# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-24 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import systems.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20161123_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='animal_ken',
            field=systems.fields.DotsField(default=0, verbose_name='Animal Ken'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='storyteller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
