# Generated by Django 2.0.2 on 2018-03-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0002_auto_20180301_1625'),
        ('sheets', '0006_auto_20180301_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterpower',
            name='power_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game_rules.PowerOption'),
        ),
    ]
