# Generated by Django 2.0.2 on 2018-04-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_healthtracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthtracker',
            options={'verbose_name': 'Health', 'verbose_name_plural': 'Health'},
        ),
        migrations.RenameField(
            model_name='healthtracker',
            old_name='character',
            new_name='health',
        ),
        migrations.RemoveField(
            model_name='healthtracker',
            name='uuid',
        ),
        migrations.AddField(
            model_name='healthtracker',
            name='resistant_damage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthtracker',
            name='aggravated_damage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthtracker',
            name='bashing_damage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthtracker',
            name='lethal_damage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
