# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20170422_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='damage_track',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
