# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20161123_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='concept',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.Template'),
        ),
    ]
