# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_auto_20170107_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterpower',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
