# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_character_damage_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='beats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
