# Generated by Django 2.0.2 on 2018-03-01 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_characterpower_power_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterpower',
            name='power_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game_rules.PowerOption', verbose_name='Option'),
        ),
    ]
