# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_auto_20170424_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterpower',
            name='details',
        ),
    ]
