# Generated by Django 2.0.2 on 2018-03-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_auto_20180301_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='experience_cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
