# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_skillspecialities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillSpecialities',
            new_name='SkillSpeciality',
        ),
        migrations.AlterModelOptions(
            name='skillspeciality',
            options={'verbose_name': 'Skill Speciality', 'verbose_name_plural': 'Skill Specialities'},
        ),
    ]
