# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_auto_20170107_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='storyteller',
        ),
    ]
