# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('sheets', '0012_remove_character_storyteller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Chronicle Name')),
                ('mood', models.CharField(blank=True, max_length=200)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('domain_storyteller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('storytelling_group', models.ManyToManyField(to='auth.Group')),
                ('venue_storyteller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
