# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_auto_20170107_2249'),
        ('sheets', '0013_chronicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronicle',
            name='default_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='systems.Template'),
        ),
    ]
