# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('sheets', '0014_chronicle_default_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronicle',
            name='storytelling_group',
        ),
        migrations.AddField(
            model_name='chronicle',
            name='storytelling_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chronicle', to='auth.Group'),
        ),
    ]
