# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0016_auto_20170108_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='approved_on',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_retired',
        ),
        migrations.RemoveField(
            model_name='character',
            name='version',
        ),
        migrations.AddField(
            model_name='character',
            name='chronicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='sheets.Chronicle'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chronicle',
            name='coordinating_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='chronicle',
            name='domain_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chronicle',
            name='domain_storyteller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chronicle',
            name='storytelling_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='chronicle',
            name='venue_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chronicle',
            name='venue_storyteller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
