# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0017_auto_20170108_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('trait_category', models.CharField(choices=[('creation', 'Creation'), ('attribute', 'Attribute'), ('skill', 'Skill'), ('speciality', 'Skill Speciality'), ('potency', 'Supernatural Potency'), ('merit', 'Merit'), ('integrity', 'Integrity'), ('power', 'Template Power'), ('other', 'Other')], max_length=20)),
                ('trait', models.CharField(max_length=40)),
                ('justification', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('experiences', models.SmallIntegerField(default=0)),
                ('old_value', models.SmallIntegerField(default=0)),
                ('new_value', models.SmallIntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='sheets.Character')),
            ],
        ),
    ]
