# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0018_approvalrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='experiences',
            new_name='experience_cost',
        ),
    ]
