# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0019_auto_20170108_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='detail',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
