# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0020_approvalrequest_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='experience_cost',
            field=models.SmallIntegerField(default=0, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='new_value',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='New'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='old_value',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Old'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='trait',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='trait_category',
            field=models.CharField(choices=[('creation', 'Creation'), ('attribute', 'Attribute'), ('skill', 'Skill'), ('speciality', 'Skill Speciality'), ('potency', 'Supernatural Potency'), ('merit', 'Merit'), ('integrity', 'Integrity'), ('power', 'Template Power'), ('other', 'Other')], max_length=20, verbose_name='Type'),
        ),
    ]
