# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0021_auto_20170109_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='available_experience',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='character',
            name='coordinator_beats',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='character',
            name='spent_experience',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='character',
            name='storyteller_beats',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='On'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Character'),
        ),
    ]
