# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0022_auto_20170109_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='coordinator_beats',
        ),
        migrations.AddField(
            model_name='character',
            name='organization_beats',
            field=models.SmallIntegerField(default=30, verbose_name='Org beats'),
        ),
        migrations.AlterField(
            model_name='character',
            name='available_experience',
            field=models.SmallIntegerField(default=6, editable=False, verbose_name='Available Exp'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spent_experience',
            field=models.SmallIntegerField(default=0, editable=False, verbose_name='Spent Exp'),
        ),
    ]
