# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0023_auto_20170109_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
