# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0024_character_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
