# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0025_auto_20170109_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='justification',
            new_name='player_notes',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='experience_cost',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='old_value',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='trait',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='trait_category',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='spent_experience',
            field=models.SmallIntegerField(default=0, verbose_name='Spent Exp'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='storyteller_notes',
            field=models.TextField(blank=True),
        ),
    ]
