# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0026_auto_20170109_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='completed_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
