# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0028_auto_20170109_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_current',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='character',
            name='tracking_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='version',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
