# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0029_auto_20170109_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='tracking_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='sheets.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_on',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
