# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0032_auto_20170110_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='storyteller_notes',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='sheets.Character'),
        ),
    ]
