# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0033_auto_20170110_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='tracking_id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='tracking_id',
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='details',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
