# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0034_auto_20170110_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='version',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
