# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0035_auto_20170110_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='sheets.Character'),
        ),
    ]
