# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0036_auto_20170110_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactermerit',
            old_name='detail',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='characterpower',
            old_name='detail',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='version',
            field=models.IntegerField(blank='', null=True),
        ),
    ]
