# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0037_auto_20170110_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='details',
            field=models.TextField(default='Empty'),
            preserve_default=False,
        ),
    ]
