# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 04:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('information', models.TextField(blank=True, help_text='Optional. Basic summary about the event that all users should know.')),
                ('external_url', models.URLField(blank=True, help_text='Optional. External link containing additional event information.', null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-event_date',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_officer', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('organization__name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. Must be unique across all Organizations.', max_length=200, unique=True)),
                ('information', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True, help_text='Allow others to search and find this organization and request membership.', verbose_name='Open to the Public')),
                ('parent_org', models.ForeignKey(blank=True, help_text='Optional. If set, you will inherit settings and staff from this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.Organization', verbose_name='Parent Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, help_text='Optional. Only shared with Organizations you join.', max_length=20)),
                ('is_verified', models.BooleanField(default=False, editable=False)),
                ('last_visit', models.DateTimeField(blank=True, editable=False, null=True)),
                ('verification_code', models.CharField(blank=True, editable=False, max_length=14, null=True)),
                ('code_sent_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('org_create_cap', models.SmallIntegerField(default=5, editable=False)),
                ('information', models.TextField(blank=True, help_text='Optional. Personal information that you want to share with Orgs.', null=True)),
            ],
            options={
                'verbose_name': 'Profile',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orgs.Organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orgs.Organization'),
        ),
        migrations.CreateModel(
            name='PublicOrganization',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('orgs.organization',),
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('orgs.event',),
            managers=[
                ('upcoming', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('user', 'organization')]),
        ),
    ]
