# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systems', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Chronicle Name')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('mood', models.CharField(blank=True, max_length=200)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('information', models.TextField(blank=True)),
                ('coordinating_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group')),
                ('default_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='systems.Template')),
                ('domain_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain_storyteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('storytelling_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.Group')),
                ('venue_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venue_storyteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Event Name')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('information', models.TextField(blank=True)),
                ('planning_document', models.URLField(blank=True)),
                ('seq', models.SmallIntegerField(editable=False, null=True)),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='orgs.Chronicle')),
            ],
            options={
                'ordering': ('-event_date',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hold', 'On Hold'), ('provisional', 'Provisional'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='provisional', max_length=20)),
                ('joined_on', models.DateField(blank=True, null=True, verbose_name='Joined')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='Starts')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='Ends')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestige_beats', models.SmallIntegerField(default=0)),
                ('details', models.TextField(blank=True)),
                ('awarded_on', models.DateField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestige', to='orgs.Membership')),
            ],
        ),
    ]
