# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='ends_on',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='starts_on',
        ),
        migrations.AddField(
            model_name='membership',
            name='renewal_on',
            field=models.DateField(blank=True, null=True, verbose_name='Renews on'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='joined_on',
            field=models.DateField(blank=True, null=True, verbose_name='Joined on'),
        ),
    ]
