# Generated by Django 2.0.2 on 2018-02-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reference_code',
            field=models.SlugField(default='', unique=True, verbose_name='URL Prefix'),
            preserve_default=False,
        ),
    ]
