# Generated by Django 2.0.2 on 2018-02-12 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional. External link containing additional information.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='information',
            field=models.TextField(blank=True, help_text='Optional. Basic summary about the event.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow finding the organization and requesting membership.', verbose_name='Open to the Public'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_org',
            field=models.ForeignKey(blank=True, help_text='Optional. If set, you will inherit settings and staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.Organization', verbose_name='Parent Organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='information',
            field=models.TextField(blank=True, help_text='Optional. Personal information shared with others.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
