# Generated by Django 2.0.2 on 2018-02-22 14:58

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpcomingEvent',
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('organization__name', 'user__username')},
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_officer',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='membership',
            name='external_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='active', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='membership',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='title',
            field=models.CharField(blank=True, choices=[('storyteller', 'Storyteller'), ('coordinator', 'Coordinator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Required. Must be unique.', max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
