# Generated by Django 2.0.2 on 2018-02-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
    ]
