# Generated by Django 2.0.2 on 2018-02-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='information',
            field=models.TextField(blank=True, help_text='Information about your organization. If you set this Organization to be public, everyone will be able to see this information.'),
        ),
    ]
