# Generated by Django 2.0.2 on 2018-02-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_organization_reference_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile'},
        ),
    ]
