# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20170405_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code_sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
