# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20170405_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
