# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0004_organization_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='rank',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('member', 'Member')], default='member', max_length=40),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=40),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Must be unique across all Organizations.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.Organization', verbose_name='Parent Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('user', 'organization')]),
        ),
    ]
