# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20170406_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow others to search and find this organization and request Membership.', verbose_name='Open to the Public'),
        ),
    ]
