# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 14:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_organization_is_public'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
    ]
