# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_auto_20170406_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOrganization',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('orgs.organization',),
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow others to search and find this organization and request membership.', verbose_name='Open to the Public'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Required. Must be unique across all Organizations.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_org',
            field=models.ForeignKey(blank=True, help_text='Optional. If set, you will inherit settings and staff from this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgs.Organization', verbose_name='Parent Organization'),
        ),
    ]
