# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_auto_20170406_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='status',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
