# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_auto_20170406_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
