# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_membership_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='information',
            field=models.TextField(blank=True, help_text='Optional. Personal information that you want to share with Orgs.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional. Only shared with Organizations you join.', max_length=20),
        ),
    ]
