# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20170407_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_create_cap',
            field=models.SmallIntegerField(default=5, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code_sent_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_visit',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, editable=False, max_length=14, null=True),
        ),
    ]
