# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_auto_20170407_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('organization__name',)},
        ),
        migrations.AddField(
            model_name='membership',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
