# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_auto_20170408_0812'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('upcoming', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='seq',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orgs.Organization'),
        ),
    ]
