# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_auto_20170409_1106'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
    ]
