# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_auto_20170409_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orgs.Event')),
            ],
            bases=('orgs.event',),
            managers=[
                ('upcoming', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional. External link containing additional event information.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='information',
            field=models.TextField(blank=True, help_text='Optional. Basic summary about the event that all users should know.'),
        ),
    ]
