# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_auto_20170409_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
