# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_auto_20170409_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingevent',
            name='event_ptr',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.DeleteModel(
            name='UpcomingEvent',
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('orgs.event',),
            managers=[
                ('upcoming', django.db.models.manager.Manager()),
            ],
        ),
    ]
