# Generated by Django 2.0.4 on 2018-04-13 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dots', models.PositiveSmallIntegerField(default=1)),
                ('merit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='game_rules.Merit')),
            ],
            options={
                'ordering': ('dots',),
            },
        ),
    ]
