# Generated by Django 2.0.2 on 2018-04-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powercategory',
            name='base_experience_cost',
        ),
        migrations.AddField(
            model_name='powercategory',
            name='experience_cost',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
