# Generated by Django 2.0.2 on 2018-03-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('power_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_options', to='game_rules.PowerCategory')),
            ],
            options={
                'ordering': ('power_category', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='poweroption',
            unique_together={('name', 'power_category')},
        ),
    ]
