# Generated by Django 2.0.2 on 2018-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powercategory',
            name='experience_cost',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='powercategory',
            name='experience_splat_cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powercategory',
            name='splat_discount_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
