# Generated by Django 2.0.4 on 2018-04-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0002_meritvariants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeritVariants',
            new_name='MeritVariant',
        ),
    ]
