# Generated by Django 2.0.2 on 2018-03-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0002_auto_20180301_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactertemplate',
            name='experiences_prefix',
        ),
    ]
