# Generated by Django 2.0.4 on 2018-04-13 03:37

from django.db import migrations
import game_rules.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0003_auto_20180412_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meritvariant',
            name='dots',
            field=game_rules.fields.DotsField(default=0),
        ),
    ]
