# Generated by Django 2.0.4 on 2018-04-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_rules', '0004_auto_20180412_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritvariant',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
