# Generated by Django 2.0.2 on 2018-02-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheets', '0001_initial'),
        ('downtime', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimeaction',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_actions', to='sheets.Character'),
        ),
        migrations.AddField(
            model_name='downtimeaction',
            name='target_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_actions', to='orgs.Event'),
        ),
    ]
