# Generated by Django 2.0.2 on 2018-02-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Anchor Category',
                'verbose_name_plural': 'Anchor Categories',
            },
        ),
        migrations.CreateModel(
            name='CharacterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('alias', models.CharField(blank=True, max_length=20)),
                ('integrity_name', models.CharField(default='Integrity', max_length=20, verbose_name='Integrity')),
                ('power_stat_name', models.CharField(max_length=20, verbose_name='Power Stat')),
                ('resource_name', models.CharField(max_length=20, verbose_name='Resource')),
                ('primary_anchor_name', models.CharField(default='Virtue', max_length=20, verbose_name='Primary Anchor')),
                ('secondary_anchor_name', models.CharField(default='Vice', max_length=20, verbose_name='Secondary Anchor')),
                ('character_group_name', models.CharField(default='Group', max_length=20, verbose_name='Group Name')),
                ('experiences_prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Experiences Prefix')),
            ],
            options={
                'verbose_name': 'Template',
            },
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.CharacterTemplate')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PowerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_categories', to='systems.CharacterTemplate')),
            ],
            options={
                'verbose_name': 'Power Category',
                'verbose_name_plural': 'Power Categories',
            },
        ),
        migrations.CreateModel(
            name='Splat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('flavor', models.CharField(choices=[('1', 'Primary (Nature)'), ('2', 'Secondary (Faction)'), ('3', 'Tertiary (Attained)')], max_length=10, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splat_categories', to='systems.CharacterTemplate')),
            ],
            options={
                'ordering': ('template', 'flavor'),
            },
        ),
        migrations.CreateModel(
            name='SplatOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splats', to='systems.Splat')),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.AddField(
            model_name='power',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powers', to='systems.PowerCategory'),
        ),
        migrations.AddField(
            model_name='anchorcategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_categories', to='systems.CharacterTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='power',
            unique_together={('name', 'category')},
        ),
    ]
