# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Anchor Categories',
                'verbose_name': 'Anchor Category',
            },
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_book', models.CharField(blank=True, max_length=100)),
                ('reference_page', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('mental', 'Mental'), ('physical', 'Physical'), ('social', 'Social'), ('supernatural', 'Supernatural'), ('style', 'Style')], max_length=20, null=True)),
            ],
            options={
                'ordering': ('template', 'category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_book', models.CharField(blank=True, max_length=100)),
                ('reference_page', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PowerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Power Categories',
                'verbose_name': 'Power Category',
            },
        ),
        migrations.CreateModel(
            name='Splat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('flavor', models.CharField(choices=[('primary', 'Primary (Nature)'), ('secondary', 'Secondary (Faction)'), ('tertiary', 'Tertiary (Attained)')], max_length=10, null=True)),
            ],
            options={
                'ordering': ('template', 'flavor'),
            },
        ),
        migrations.CreateModel(
            name='SplatOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_book', models.CharField(blank=True, max_length=100)),
                ('reference_page', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splats', to='systems.Splat')),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('alias', models.CharField(blank=True, max_length=20)),
                ('integrity_name', models.CharField(default='Integrity', max_length=20, verbose_name='Integrity')),
                ('power_stat_name', models.CharField(max_length=20, verbose_name='Power Stat')),
                ('resource_name', models.CharField(max_length=20, verbose_name='Resource')),
                ('primary_anchor_name', models.CharField(default='Virtue', max_length=20, verbose_name='Primary Anchor')),
                ('secondary_anchor_name', models.CharField(default='Vice', max_length=20, verbose_name='Secondary Anchor')),
                ('character_group_name', models.CharField(default='Group', max_length=20, verbose_name='Group Name')),
            ],
        ),
        migrations.AddField(
            model_name='splat',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splat_categories', to='systems.Template'),
        ),
        migrations.AddField(
            model_name='powercategory',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_categories', to='systems.Template'),
        ),
        migrations.AddField(
            model_name='power',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='powers', to='systems.PowerCategory'),
        ),
        migrations.AddField(
            model_name='merit',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.Template'),
        ),
        migrations.AddField(
            model_name='anchorcategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_categories', to='systems.Template'),
        ),
        migrations.AlterUniqueTogether(
            name='power',
            unique_together=set([('name', 'category')]),
        ),
    ]
