# Generated by Django 2.0.2 on 2018-02-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merit',
            name='category',
            field=models.CharField(choices=[('mental', 'Mental'), ('physical', 'Physical'), ('social', 'Social'), ('supernatural', 'Supernatural'), ('style', 'Style')], default='mental', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merit',
            name='reference_code',
            field=models.SlugField(default='', unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merit',
            name='character_template',
            field=models.ForeignKey(blank=True, help_text='Optional. Restricts Merit to specific a Template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='systems.CharacterTemplate', verbose_name='Template Restriction'),
        ),
    ]
