# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powercategory',
            name='template',
        ),
        migrations.AddField(
            model_name='powercategory',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_categories', to='systems.Template'),
        ),
    ]
