# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splat',
            name='flavor',
            field=models.CharField(choices=[('1', 'Primary (Nature)'), ('2', 'Secondary (Faction)'), ('3', 'Tertiary (Attained)')], max_length=10, null=True),
        ),
    ]
