# Generated by Django 2.0.2 on 2018-02-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertemplate',
            name='reference_code',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='splat',
            unique_together={('template', 'flavor')},
        ),
    ]
