# Generated by Django 2.0.2 on 2018-02-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertemplate',
            name='power_stat_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Power Stat'),
        ),
        migrations.AlterField(
            model_name='charactertemplate',
            name='resource_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Resource'),
        ),
    ]
