# Generated by Django 2.0.2 on 2018-02-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='origin_splat',
        ),
    ]
