# Generated by Django 2.0.2 on 2018-02-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeprerequisite',
            name='merit',
        ),
        migrations.RemoveField(
            model_name='attributeprerequisite',
            name='prerequisite_ptr',
        ),
        migrations.DeleteModel(
            name='AttributePrerequisite',
        ),
        migrations.DeleteModel(
            name='Prerequisite',
        ),
    ]
