# Generated by Django 2.0.2 on 2018-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20180216_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reference_code', models.SlugField(max_length=10, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Reference Book',
            },
        ),
        migrations.AlterField(
            model_name='merit',
            name='category',
            field=models.CharField(choices=[('mental', 'Mental'), ('physical', 'Physical'), ('social', 'Social'), ('supernatural', 'Supernatural'), ('style', 'Style'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='splatcategory',
            name='flavor',
            field=models.CharField(choices=[('1', 'Primary (Nature)'), ('2', 'Secondary (Faction)'), ('3', 'Tertiary (Attained)')], max_length=1, null=True),
        ),
    ]
