# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20161122_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ('category', 'name')},
        ),
        migrations.RemoveField(
            model_name='merit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='power',
            name='description',
        ),
        migrations.RemoveField(
            model_name='splatoption',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='splatoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='splatoption',
            name='is_playable',
        ),
        migrations.AddField(
            model_name='merit',
            name='reference_book',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merit',
            name='reference_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='power',
            name='reference_book',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='power',
            name='reference_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='splatoption',
            name='reference_book',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='splatoption',
            name='reference_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
