# Generated by Django 2.0.2 on 2018-02-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20180216_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactertemplate',
            options={'ordering': ('name', 'game_line'), 'verbose_name': 'Character Template'},
        ),
    ]
