# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20160311_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='splat',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
