# Generated by Django 2.0.2 on 2018-02-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20180215_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='splatcategory',
            options={'ordering': ('character_template', 'flavor'), 'verbose_name': 'Splat Category', 'verbose_name_plural': 'Splat Categories'},
        ),
        migrations.AlterField(
            model_name='power',
            name='power_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='systems.PowerCategory'),
        ),
        migrations.AlterField(
            model_name='powercategory',
            name='character_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_categories', to='systems.CharacterTemplate'),
        ),
    ]
