# Generated by Django 2.0.2 on 2018-02-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20180214_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactertemplate',
            options={'verbose_name': 'Character Template'},
        ),
        migrations.RenameField(
            model_name='charactertemplate',
            old_name='alias',
            new_name='game_line',
        ),
        migrations.AlterField(
            model_name='charactertemplate',
            name='reference_code',
            field=models.SlugField(verbose_name='Code'),
        ),
    ]
