# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20170412_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merit',
            options={'ordering': ('template', 'name')},
        ),
        migrations.RemoveField(
            model_name='merit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='merit',
            name='reference_book',
        ),
        migrations.RemoveField(
            model_name='merit',
            name='reference_page',
        ),
        migrations.RemoveField(
            model_name='power',
            name='reference_book',
        ),
        migrations.RemoveField(
            model_name='power',
            name='reference_page',
        ),
        migrations.RemoveField(
            model_name='splatoption',
            name='reference_book',
        ),
        migrations.RemoveField(
            model_name='splatoption',
            name='reference_page',
        ),
    ]
