# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20170414_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merit',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
