# Generated by Django 2.0.2 on 2018-02-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20180216_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='origin_splat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='systems.Splat'),
        ),
    ]
