# Generated by Django 2.0.2 on 2018-02-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20180214_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertemplate',
            name='game_line',
            field=models.CharField(max_length=20),
        ),
    ]
