# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_auto_20160312_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anchorcategory',
            options={'verbose_name': 'Anchor Category', 'verbose_name_plural': 'Anchor Categories'},
        ),
        migrations.AlterModelOptions(
            name='powercategory',
            options={'verbose_name': 'Power Category', 'verbose_name_plural': 'Power Categories'},
        ),
        migrations.AlterModelOptions(
            name='splatcategory',
            options={'verbose_name': 'Splat Category', 'verbose_name_plural': 'Splat Categories'},
        ),
        migrations.RemoveField(
            model_name='splatcategory',
            name='alias',
        ),
        migrations.AddField(
            model_name='splat',
            name='alias',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
