# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_auto_20170414_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merit',
            options={'ordering': ('name',)},
        ),
    ]
