# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_auto_20170414_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertemplate',
            name='experiences_prefix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Experiences Prefix'),
        ),
    ]
