# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_splatcategory_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='splatcategory',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
