# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_splatcategory_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='splat',
            name='is_playable',
            field=models.BooleanField(default=True),
        ),
    ]
