# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-22 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_remove_splat_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='splat',
            options={'ordering': ('category', 'name')},
        ),
        migrations.AlterField(
            model_name='splat',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='splatcategory',
            name='is_editable',
            field=models.BooleanField(default=True, verbose_name='Splat can be changed after assigned'),
        ),
        migrations.AlterField(
            model_name='splatcategory',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Splat is required on creation'),
        ),
    ]
